### ISSUE TITLE
Why Chinese?

### ISSUE THREAD

**Issue by ooker777** [deepakshrma/30-seconds-of-typescript#38]
I have no problem with it, just being curiosity. You seem to be an Indian, so isn't that it's more natural for you to support Hindi?

**Comment by deepakshrma** [comment]
In India, there is no common language among the masses. However, most colleges in India teach English as a second language, so I firmly believe that the majority of Indians are proficient in English. I never considered the need for Hindi documents, but even a video explanation may have its limitations. Therefore, I am confident that English documents should suffice.

But noted.. Will see demands in Hindi. 

Thank you for pointing that out.

**Comment by ooker777** [comment]
Oh, I thought that Hindi is the native language of most Indian. My bad. I see why there is no need for Hindi. Still, I wonder why you choose Chinese as the second language of the site?
